import type { Metadata } from "next";
import { Press_Start_2P, Noto_Serif } from "next/font/google";
import "./globals.css";

const pressStart2P = Press_Start_2P({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-press-start',
  display: 'swap',
});

const noto = Noto_Serif({
  subsets: ["latin"],
  weight: ["100","200","300","400","500","600","700","800","900"],
  variable: '--font-noto-serif',
  display: 'swap',
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${pressStart2P.variable} ${noto.variable}`}>
      <body className="font-gameboy">
        {children}
      </body>
    </html>
  );
}
